version: 1
update_configs:
  - package_manager: "rust:cargo"
    directory: "/"
    update_schedule: "daily"
    target_branch: "master"
    allowed_updates:
      - match:
          update_type: "all"
    version_requirement_updates: "auto"
    default_reviewers:
      - "Aedius"